<?xml version="1.0" encoding="utf-8"?><workItemType dslVersion="12.0.0.0" Name="Test Plan" source="E:\projects\semstfs\DefaultCollection\etfs\process template\ETFS - Microsoft Visual Studio Scrum 2013.3\WorkItem Tracking\TypeDefinitions\TestPlan.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner" />