<?xml version="1.0" encoding="utf-8"?><workItemType dslVersion="14.0.0.0" Name="Bug" source="C:\eTFS\process template\Team Project Customizations\Cloud\Workitem Tracking\TypeDefinitions\Bug.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner" />